[build-system]
requires = ["setuptools", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"


[project]
name = "matrixcore"
description = "A modern python matrix SDK"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.10"
license = { text = "Apache 2.0" }
authors = [
    {name = "Nexus", email = "pip@nexy7574.co.uk"}
]
dynamic = ["version"]
dependencies = [
    "httpx[http2]~=0.28",
    "pydantic~=2.10",
    "tzdata>=2024.2"
]

#classifiers = [
#    "Development Status :: 5 - Production/Stable",
#    "Intended Audience :: Developers",
#    "Natural Language :: English",
#    "Operating System :: Microsoft :: Windows",
#    "Operating System :: POSIX",
#    "Programming Language :: Python :: 3 :: Only",
#    "Programming Language :: Python :: 3.10",
#    "Programming Language :: Python :: 3.11",
#    "Programming Language :: Python :: 3.12",
#    "Programming Language :: Python :: Implementation :: CPython",
#    "Topic :: Communications",
#    "Topic :: Internet",
#    "Topic :: Software Development :: Libraries",
#    "Topic :: Software Development :: Libraries :: Application Frameworks",
#    "Topic :: Utilities"
#]

[project.urls]
Source = "https://github.com/nexy7574/matrixcore"
Tracker = "https://github.com/nexy7574/matrixcore/issues"
"Matrix Room" = "https://matrix.to/#/#niobot:nexy7574.co.uk"
Funding = "https://ko-fi.com/nexy7574"
Homepage = "https://matrixcore.dev"

[project.optional-dependencies]
dev = [
    'mkdocs',
    'mkdocs-material',
    'black',
    'mkdocs-autorefs',
    'mkdocs-glightbox',
    'mkdocstrings[python]',
    'mkdocs-git-revision-date-localized-plugin',
    'isort',
    'build',
    'pep440',
    'pycodestyle',
    'pytest',
    'pytest-asyncio',
    'pytest-benchmark',
    'pytest-dependency',
    'ruff>=0.8',
    'mike',
    'pre-commit'
]

[project.scripts]
niocli = "matrixcore.__main__:cli_root [cli]"

[tool.setuptools_scm]
write_to = "src/matrixcore/__version__.py"

[tool.black]
line-length = 120
target-versions = ["py310", "py311", "py312", "py313"]
include = 'src/matrixcore'

[tool.isort]
profile = "black"
src_paths = ["src/matrixcore"]

[tool.pytest.ini_options]
testpaths = [
    "src",
]

[tool.ruff]
exclude = [".git", "examples"]
target-version = "py39"
line-length = 120
indent-width = 4
respect-gitignore = true

[tool.ruff.lint]
fixable = ["ALL"]
ignore =   ["F403", "F405"]
select = ["E", "F"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"


[tool.ruff.lint.isort]
case-sensitive = true
combine-as-imports = true
detect-same-package = true

[tool.ruff.lint.pycodestyle]
max-doc-length = 120
max-line-length = 120
