# Copyright 2025 nexy7574 <https://github.com/nexy7574>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import typing

from pydantic import BaseModel, ConfigDict, Field

from .lib import RoomPredecessor

__all__ = [
    "MRoomMessage",
    "MRoomName",
    "MRoomTopic",
    "MRoomAvatar",
    "MRoomPinnedEvents",
    "MRoomRedaction",
    "MRoomCreate",
    "MRoomJoinRules",
    "MRoomCanonicalAlias",
    "MRoomEncryption",
    "StrippedStateEvent",
    "ClientEvent",
    "ClientEventWithoutRoomID",
    "MRoomGuestAccess",
    "MRoomHistoryVisibility",
    "MRoomPowerLevels",
    "MRoomMember",
]

from ..media import MXCUri


class ClientEventWithoutRoomID(BaseModel):
    """
    The format used for events when they are returned from a homeserver to a client via the Client-Server API,
    or sent to an Application Service via the Application Services API.
    """

    class UnsignedData(BaseModel):
        age: int = None
        """
        The time in milliseconds that has elapsed since the event was sent. 
        This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the
        two servers is out of sync, which can cause the age to either be negative or greater than it actually is.
        """
        membership: str = None
        """The room membership of the user making the request, at the time of the event. Generally not used."""
        prev_content: dict[str, typing.Any] = None
        """
        The previous content for this event
        This field is generated by the local homeserver, and is only returned if the event is a state event,
        and the client has permission to see the previous content.
        """
        redacted_because: typing.Union["ClientEventWithoutRoomID", "ClientEvent"] = None
        """The event that redacted this one, if any."""
        transaction_id: str = None
        """The client-supplied transaction ID, if the client being given the event is the same one which sent it."""
        replaces_state: str = None
        """The event ID of the previous state of this state event."""

    content: dict[str, typing.Any]
    """The body of this event, as created by the client which sent it."""
    event_id: str
    """The globally unique identifier for this event."""
    origin_server_ts: int
    """Timestamp (in milliseconds since the unix epoch) on originating homeserver when this event was sent."""
    sender: str
    """Contains the fully-qualified ID of the user who sent this event."""
    state_key: str = None
    """
    Present if, and only if, this event is a state event. The key making this piece of state unique in the room.
    Note that it is often an empty string.

    State keys starting with an @ are reserved for referencing user IDs, such as room members. 
    With the exception of a few events, state events set with a given user’s ID as the state key MUST only be set by
    that user.
    """
    type: str
    """the type of the event."""
    unsigned: UnsignedData = None
    """Contains optional extra information about the event."""

    def __hash__(self):
        return hash((self.event_id, self.type, self.state_key or ''))

    def __eq__(self, other):
        return hasattr(other, "event_id") and self.event_id == other.event_id


class ClientEvent(ClientEventWithoutRoomID):
    """
    The format used for events when they are returned from a homeserver to a client via the Client-Server API,
    or sent to an Application Service via the Application Services API.
    """

    room_id: str
    """The ID of the room associated with this event."""

    def __hash__(self):
        return hash((self.event_id, self.type, self.state_key or '', self.room_id))

    def __eq__(self, other):
        return (
            hasattr(other, "event_id") and self.event_id == other.event_id
            and hasattr(other, "room_id") and self.room_id == other.room_id
        )


class StrippedStateEvent(BaseModel):
    """
    A stripped-down version of the Event format, primarily used for sending state events to clients.

    See: https://spec.matrix.org/v1.13/client-server-api/#stripped-state
    """

    content: dict[
        str,
        typing.Union[
            "MRoomCreate",
            "MRoomName",
            "MRoomAvatar",
            "MRoomTopic",
            "MRoomJoinRules",
            "MRoomCanonicalAlias",
            "MRoomEncryption",
        ],
    ]
    """The content of the event."""
    sender: str
    """The user ID of the sender of the event."""
    state_key: str
    """
    A key which defines the state type of the event. For example, a key of 'foo' would represent a state event of type
    'm.room.state.foo'.
    """
    type: str
    """The type of the event."""

    def __hash__(self):
        return hash((self.type, self.state_key))

    def __eq__(self, other):
        return (
            hasattr(other, "type") and self.type == other.type
            and hasattr(other, "state_key") and self.state_key == other.state_key
            and hasattr(other, "content") and other.content == self.content
        )


class MRoomCreate(BaseModel):
    """Represents the body of an m.room.create event"""

    creator: str = None
    """
    The user_id of the room creator.
    Required for, and only present in, room versions 1 - 10.
    Starting with room version 11 the event sender should be used instead.
    """
    federate: bool = Field(default=True, alias="m.federate")
    """Whether users on other homeservers are allowed to join this room."""
    predecessor: RoomPredecessor = None
    """A reference to the room that this room replaces, if the previous room was upgraded."""
    room_version: str = "1"  # mfw default is an insecure version
    """The version of the room. Defaults to "1"."""
    type: str = None
    """
    Optional room type to denote a room’s intended function outside of traditional conversation.
    
    Unspecified room types are possible using Namespaced Identifiers.
    """


class MRoomJoinRules(BaseModel):
    """Represents the body of an m.room.join_rules event"""

    class AllowCondition(BaseModel):
        room_id: str = None
        """
        Required if type is m.room_membership. The room ID to check the user’s membership against.
        If the user is joined to this room, they satisfy the condition and thus are permitted to join the restricted
        room.
        """
        type: typing.Literal["m.room_membership"]
        """The type of event to allow. This should be m.room_membership."""

    allow: list[AllowCondition] = None
    """A list of allow conditions required to join."""
    join_rule: typing.Literal["public", "knock", "invite", "restricted", "knock_restricted", "private"]
    """The join rule"""


class MRoomHistoryVisibility(BaseModel):
    """Represents the body of an m.room.history_visibility event"""

    history_visibility: typing.Literal["invited", "joined", "shared", "world_readable"]


class MRoomGuestAccess(BaseModel):
    """Represents the body of an m.room.guest_access event"""

    guest_access: typing.Literal["can_join", "forbidden"]


class MRoomCanonicalAlias(BaseModel):
    """Represents the body of an m.room.canonical_alias event"""

    alias: str = None
    """
    The canonical alias for the room.
    
    If not present, null, or empty the room should be considered to have no canonical alias.
    """

    alt_aliases: list[str] = None
    """
    Alternative aliases the room advertises. 
    This list can have aliases despite the alias field being null, empty, or otherwise not present.
    """


class MRoomEncryption(BaseModel):
    algorithm: typing.Literal["m.megolm.v1.aes-sha2"]
    """The encryption algorithm used for encryption in this room."""
    rotation_period_ms: int = 604800000
    """How long the session should be used before changing it. Defaults to 1 week."""
    rotation_period_msgs: int = 100
    """How many messages should be sent before changing the session. 100 is the default."""


class MRoomMessage(BaseModel):
    """Represents the body of an m.room.message event"""

    model_config = ConfigDict(extra="allow")

    body: str
    msgtype: str
    format: str = None
    formatted_body: str = None


class MRoomName(BaseModel):
    """Represents the body of an m.room.name event"""

    name: str


class MRoomTopic(BaseModel):
    """Represents the body of an m.room.topic event"""

    topic: str


class MRoomAvatar(BaseModel):
    """Represents the body of an m.room.avatar event"""

    class AvatarInfo(BaseModel):
        class ThumbnailInfo(BaseModel):
            h: int = None
            w: int = None
            mimetype: str = None
            size: int = None

        h: int = None
        w: int = None
        mimetype: str = None
        size: int = None
        thumbnail_info: ThumbnailInfo = None
        thumbnail_url: MXCUri = None

    info: AvatarInfo = None
    url: MXCUri = None


class MRoomPinnedEvents(BaseModel):
    """Represents the body of an m.room.pinned_events event"""

    pinned: list[str]


class MRoomRedaction(BaseModel):
    """Represents the body of an m.room.redaction event"""

    reason: str = None
    redacts: str = None  # may be omitted in room versions <11


class MRoomMember(BaseModel):
    """Represents the body of an m.room.member event"""

    class ThirdPartyInvite(BaseModel):
        display_name: str

        class Signed(BaseModel):
            mxid: str
            signatures: dict[str, dict[str, str]]
            token: str

    membership: typing.Literal["join", "leave", "ban", "invite", "knock"]
    displayname: str | None = None
    avatar_url: MXCUri = None
    is_direct: bool = None
    join_authorised_via_users_server: str = None
    """
    Usually found on join events, this field is used to denote which homeserver
    (through representation of a user with sufficient power level) authorised the user’s join.
    More information about this field can be found in the Restricted Rooms Specification.

    Client and server implementations should be aware of the signing implications of including this field in further
    events: in particular, the event must be signed by the server which owns the user ID in the field.
    When copying the membership event’s content (for profile updates and similar) it is therefore encouraged
    to exclude this field in the copy, as otherwise the event might fail event authorization.
    """
    third_party_invite: ThirdPartyInvite = None
    reason: str | None = None


class MRoomPowerLevels(BaseModel):
    """Represents the power levels for a room."""

    # This event specifies the minimum level a user must have in order to perform a certain action.
    # It also specifies the levels of each user in the room.
    #
    # If a user_id is in the users list, then that user_id has the associated power level.
    # Otherwise they have the default level users_default. If users_default is not supplied, it is assumed to be 0.
    # If the room contains no m.room.power_levels event, the room’s creator has a power level of 100,
    # and all other users have a power level of 0.
    #
    # The level required to send a certain event is governed by events, state_default and events_default.
    # If an event type is specified in events, then the user must have at least the level specified in order to send
    # that event. If the event type is not supplied, it defaults to events_default for Message Events and state_default
    # for State Events.
    #
    # If there is no state_default in the m.room.power_levels event, or there is no m.room.power_levels event,
    # the state_default is 50. If there is no events_default in the m.room.power_levels event, or there is no
    # m.room.power_levels event, the events_default is 0.
    #
    # The power level required to invite a user to the room, kick a user from the room, ban a user from the room,
    # or redact an event sent by another user, is defined by invite, kick, ban, and redact, respectively.
    # The levels for kick, ban and redact default to 50 if they are not specified in the m.room.power_levels event,
    # or if the room contains no m.room.power_levels event. invite defaults to 0 in either case.
    #
    # Note:
    #
    # The allowed range for power level values is [-(2**53)+1, (2**53)-1], as required by the Canonical JSON
    # specification.
    __MAX_VALUE = (2**53) - 1
    __MIN_VALUE = -(2**53) + 1

    events_default: int = Field(0, ge=__MIN_VALUE, le=__MAX_VALUE)
    state_default: int = Field(50, ge=__MIN_VALUE, le=__MAX_VALUE)
    users_default: int = Field(0, ge=__MIN_VALUE, le=__MAX_VALUE)
    invite: int = Field(0, ge=__MIN_VALUE, le=__MAX_VALUE)
    kick: int = Field(50, ge=__MIN_VALUE, le=__MAX_VALUE)
    ban: int = Field(default=50, ge=__MIN_VALUE, le=__MAX_VALUE)
    """The level required to ban a user."""
    redact: int = Field(50, ge=__MIN_VALUE, le=__MAX_VALUE)
    """The level required to redact an event sent by another user."""

    # v For some reason, PyCharm complains about the default value being mutable, even though it isn't.
    # noinspection PyDataclass
    notifications: dict[typing.Literal["room"] | str, int] = Field(default_factory=lambda: {"room": 50})
    """
    The power level requirements for specific notification types.
    This is a mapping from key to power level for that notifications key.
    """
    # noinspection PyDataclass
    users: dict[str, int] = Field(default_factory=dict)
    """The power levels for specific users. This is a mapping from user_id to power level for that user."""
    # noinspection PyDataclass
    events: dict[str, int] = Field(default_factory=dict)
    """The level required to send specific event types. This is a mapping from event type to power level required."""

    def get_user_power_level(self, user_id: str) -> int:
        """
        Gets the power level of the given user.
        """
        return self.users.get(user_id, self.users_default)

    def get_event_power_level(self, event: str) -> int:
        """
        Gets the power level required to send the given event.
        """
        return self.events.get(event, self.events_default)

    def get_state_event_power_level(self, event: str) -> int:
        """
        Gets the power level required to send the given state event.
        """
        return self.events.get(event, self.state_default)

    def get_notification_power_level(self, notification: str) -> int:
        """
        Gets the power level required to send the given notification.
        """
        # The spec doesn't actually define what the default PL for notifications should be,
        # but room defaults to 50, so we'll assume all other unspecified ones do too.
        return self.notifications.get(notification, 50)

    def user_can_send_event(self, user_id: str, event: str) -> bool:
        """
        Checks the power levels to see if the given user id can send the supplied event.

        State events should use get_state_event_power_level instead.
        """
        user_pl = self.get_user_power_level(user_id)
        match event:
            case "ban":
                target_pl = self.ban
            case "kick":
                target_pl = self.kick
            case "redact":
                target_pl = self.redact
            case "invite":
                target_pl = self.invite
            case _:
                target_pl = self.get_event_power_level(event)

        return user_pl >= target_pl

    def user_can_send_state_event(self, user_id: str, event: str) -> bool:
        """
        Checks the power levels to see if the given user id can send the supplied state event.
        """
        user_pl = self.get_user_power_level(user_id)
        target_pl = self.get_state_event_power_level(event)
        return user_pl >= target_pl

    def user_can_redact_event(self, user_id: str, sender: str = None) -> bool:
        """
        Checks if the user can redact an event, optionally by another user.
        """
        if sender:
            return self.user_can_send_event(user_id, "m.room.redact")
        return self.get_user_power_level(user_id) >= self.redact

    def user_can_send_notification(self, user_id: str, notification_type: str) -> bool:
        """
        Checks if the user can send the given notification type.
        """
        return self.get_user_power_level(user_id) >= self.get_notification_power_level(notification_type)
